# Generated by Django 3.2 on 2021-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user2',
            field=models.CharField(max_length=50),
        ),
    ]
