# Generated by Django 3.2 on 2021-07-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_group_groupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_name',
            new_name='group',
        ),
    ]
