# Generated by Django 3.2 on 2021-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.IntegerField(default=0),
        ),
    ]
