# Generated by Django 3.2 on 2021-07-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_groupmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='GroupThread',
        ),
    ]
