# Generated by Django 3.2 on 2021-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20210724_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='ui_align',
            field=models.IntegerField(default=0),
        ),
    ]
