# Generated by Django 3.2 on 2021-07-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_threadmessage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='chat',
        ),
    ]
